inspectIT/inspectIT

- Commons/resources/installer/installer-commons/install.xml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/26)
> INSPECTIT-1929: Fixed izpack configuration file.

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/core/ICoreService.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/core/impl/CoreService.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/AbstractPlatformSensor.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/ClassLoadingInformation.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/CompilationInformation.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/CpuInformation.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/IPlatformSensor.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/MemoryInformation.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/RuntimeInformation.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/SystemInformation.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/platform/ThreadInformation.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/core/impl/CoreServiceTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/AbstractPlatformSensorFakeImpl.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/AbstractPlatformSensorTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/ClassLoadingInformationTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CompilationInformationTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuInformationTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/CpuUsageCalculatorTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/MemoryInformationTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/RuntimeInformationTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/SystemInformationTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/platform/ThreadInformationTest.java
- inspectit.server/src/test/java/rocks/inspectit/server/rmi/KryoNetIntegrationTest.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/RuntimeInformationData.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/SystemInformationData.java
- inspectit.shared.all/src/main/resources/schema/RuntimeInformationData.sch
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/editor/text/input/VmSummaryInputController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/148)
> INSPECTIT-2084: Decouple platform sensors from central data structure.

- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/CmrRestfulService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/InvocationSequenceRestfulService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/PlatformRestfulService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/StorageRestfulService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/161)
> INSPECTIT-2186: Restructure REST endpoints

- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/analyzer/impl/ByteCodeAnalyzerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/169)
> INSPECTIT-2223: Clear interrupted state on test exit

- inspectit.server/src/main/java/rocks/inspectit/server/alerting/AlertingScheduler.java
- inspectit.server/src/test/java/rocks/inspectit/server/alerting/AlertingSchedulerTest.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/storage/serializer/impl/SerializationManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/178)
> INSPECTIT-2236: fixed deleting of alerting definitions

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/method/jdbc/ConnectionMetaDataStorage.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/jdbc/JDBCUrlExtractorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/183)
> INSPECTIT-2244: fixed NPE when URL is not specified

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/view/InstrumentationManagerViewPart.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/184)
> INSPECTIT-2242: Fixed popup menu in the instrumentation manager view

- inspectit.server/src/main/java/rocks/inspectit/server/mail/EMailSender.java
- inspectit.server/src/test/java/rocks/inspectit/server/mail/EMailSenderTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/188)
> INSPECTIT-2263: Additional SMTP properties are not used

- inspectit.server/src/main/external-resources/config/default.xml
- inspectit.server/src/main/java/rocks/inspectit/server/mail/EMailSender.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/189)
> INSPECTIT-2264: SMTP property keys contain a typo

- inspectit.server/src/main/external-resources/templates/alert-bt-closed.html
- inspectit.server/src/main/external-resources/templates/alert-bt-closed.txt
- inspectit.server/src/main/external-resources/templates/alert-bt-open.html
- inspectit.server/src/main/external-resources/templates/alert-bt-open.txt
- inspectit.server/src/main/external-resources/templates/alert-closed.html
- inspectit.server/src/main/external-resources/templates/alert-closed.txt
- inspectit.server/src/main/external-resources/templates/alert-open.html
- inspectit.server/src/main/external-resources/templates/alert-open.txt
- inspectit.server/src/main/java/rocks/inspectit/server/template/AlertEMailTemplateType.java
- inspectit.server/src/main/java/rocks/inspectit/server/template/EMailTemplateResolver.java
- inspectit.server/src/test/java/rocks/inspectit/server/template/EMailTemplateResolverTest.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/AlertingDefinition.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/198)
> INSPECTIT-2256: ThresholdType missing in alert e-mail

- inspectit.server/src/main/java/rocks/inspectit/server/dao/InvocationDataDao.java
- inspectit.server/src/main/java/rocks/inspectit/server/dao/impl/BufferInvocationDataDaoImpl.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/InvocationDataAccessService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/BusinessContextDefinitionRestfulService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/BusinessContextRestfultService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/InvocationSequenceRestfulService.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/HttpInfo.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/InvocationSequenceData.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/TimerData.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/cmr/BusinessTransactionData.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/expression/AbstractExpression.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/expression/IContainerExpression.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/expression/impl/AndExpression.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/expression/impl/BooleanExpression.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/expression/impl/NotExpression.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/expression/impl/OrExpression.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/expression/impl/StringMatchingExpression.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/impl/ApplicationDefinition.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/valuesource/StringValueSource.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/cmr/service/IInvocationDataAccessService.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/indexing/query/factory/impl/InvocationSequenceDataQueryFactory.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/service/storage/StorageInvocationDataAccessService.java
Caution: based on INSPECTIT-2186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/166)
> INSPECTIT-2215: Extend Restful API for BusinessTransactions

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/service/storage/StorageInvocationDataAccessService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/203)
> INSPECTIT-2215: fixed checkstyle warnings

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/IAgent.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/SpringAgent.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/analyzer/impl/ByteCodeAnalyzer.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/javaagent/JavaAgent.java
- inspectit.agent.java/src/main/resources/META-INF/MANIFEST.MF
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/175)
> INSPECTIT-2231: Using re-transform when analyzing already loaded classes

- inspectit.shared.all/src/test/java/rocks/inspectit/shared/all/storage/nio/stream/SocketExtendedByteBufferInputStreamTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/202)
> INSPECTIT-2288: Fixed SocketExtendedByteBufferInputStreamTest

- inspectit.server/src/main/java/rocks/inspectit/server/ci/ConfigurationInterfaceManager.java
- inspectit.shared.cs/.classpath
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/jaxb/ISchemaVersionAware.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/jaxb/JAXBTransformator.java
- inspectit.shared.cs/src/test/java/rocks/inspectit/shared/cs/jaxb/JAXBTransformatorTest.java
- inspectit.shared.cs/src/test/java/rocks/inspectit/shared/cs/jaxb/TestData.java
- inspectit.shared.cs/src/test/resources/rocks/inspectit/shared/cs/jaxb/migration/migration.xml
- inspectit.shared.cs/src/test/resources/rocks/inspectit/shared/cs/jaxb/schema.xsd
- inspectit.shared.cs/src/test/resources/rocks/inspectit/shared/cs/jaxb/schemaInvalid.xsd
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/206)
> INSPECTIT-2290: Fixed XML migration when rewriting

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/IAgent.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/IThreadTransformHelper.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/SpringAgent.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/ThreadLocalTransformHelper.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/analyzer/impl/AnalyzeCallable.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/AgentAwareClient.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/core/impl/CoreService.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/javaagent/JavaAgent.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sending/impl/TimeStrategy.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/spring/SpringConfiguration.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/util/AgentAwareThread.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/analyzer/impl/ByteCodeAnalyzerTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sending/impl/TimeStrategyTest.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/kryonet/Client.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/204)
> INSPECTIT-2289: Client thread not to transform the any class

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/instrumentation/RetransformManager.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/instrumentation/RetransformManagerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/211)
> INSPECTIT-2293: RetransformManager is not able to trigger retransformation

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/editor/tree/input/SqlInputController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/223)
> INSPECTIT-2285: Database view sort by Duration is broken

- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/jaxb/JAXBTransformator.java
- inspectit.shared.cs/src/test/java/rocks/inspectit/shared/cs/jaxb/JAXBTransformatorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/235)
> INSPECTIT-2328: Configuration file update preserves symbolic links

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KeepAliveManager.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/connection/impl/KeepAliveManagerTest.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/cmr/service/IKeepAliveService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/239)
> INSPECTIT-2335: Agent reconnects happens in milliseconds intervals

- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/HttpInfo.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/details/generator/impl/HttpDetailsGenerator.java
Fixes #241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/242)
> INSPECTIT-2340: Fixed NPE in Http details generator

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/core/ListListener.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/core/impl/CoreService.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sending/impl/ListSizeStrategy.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/method/http/HttpHook.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/method/logging/Log4JLoggingHook.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/core/impl/CoreServiceTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sending/impl/ListSizeStrategyTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/http/HttpHookTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/logging/Log4JLoggingHookTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/267)
> INSPECTIT-2370: Solve collisions in the CoreService when adding sensor data

- dependencies.gradle
- inspectit.agent.java.sdk/inspectit.agent.java.sdk.gradle
- inspectit.root.gradle
- properties.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/236)
> INSPECTIT-2331: JMH version is changeable in Gradle

- inspectit.shared.all/src/test/java/rocks/inspectit/shared/all/storage/nio/stream/SocketExtendedByteBufferInputStreamTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/272)
> INSPECTIT-2402: Fixed SocketExtendedByteBufferInputStreamTest read test

- inspectit.server/src/main/external-resources/ci/profiles/common/remote-http.xml
- inspectit.server/src/main/external-resources/ci/profiles/common/remote-jms.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/279)
> INSPECTIT-2423: Remote profiles to be default

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/268)
> INSPECTIT-2398: Latest updates for the README.MD

- inspectit.server/src/main/external-resources/config/default.xml
- inspectit.server/src/main/java/rocks/inspectit/server/influx/dao/InfluxDBDao.java
- inspectit.server/src/main/java/rocks/inspectit/server/influx/util/InfluxClientFactory.java
- inspectit.server/src/test/java/rocks/inspectit/server/influx/util/InfluxClientFactoryTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/282)
> INSPECTIT-2427: Enabled SSL support for influxDB connection

- inspectit.server/src/main/java/rocks/inspectit/server/dao/StorageDataDao.java
- inspectit.server/src/main/java/rocks/inspectit/server/dao/impl/StorageDataDaoImpl.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/StorageService.java
- inspectit.server/src/main/java/rocks/inspectit/server/storage/CmrStorageManager.java
- inspectit.server/src/test/java/rocks/inspectit/server/storage/CmrStorageManagerTest.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/cmr/service/IStorageService.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/handlers/OpenTraceOverviewHandler.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/StorageRepositoryDefinition.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/service/storage/StorageServiceProvider.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/service/storage/StorageSpanService.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/wizard/CopyDataToStorageWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/wizard/page/DefineDataProcessorsWizardPage.java
- inspectit.ui.rcp/src/main/resources/META-INF/spring/spring-context-model-storage.xml
- inspectit.ui.rcp/src/main/resources/plugin.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/277)
> INSPECTIT-2404: Saving tracing spans to storage

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/editor/tree/input/SqlInvocInputController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/283)
> INSPECTIT-2429: Fixed sorting of SQL invoc sub-view in raw mode

- inspectit.agent.java/src/jmh/java/rocks/inspectit/agent/java/instrumentation/asm/ClassInstrumenterPerfTest.java
- inspectit.root.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/273)
> INSPECTIT-2403: Fixed ClassInstrumenterPerfTest

- inspectit.agent.java.sdk/src/main/java/rocks/inspectit/agent/java/sdk/opentracing/internal/impl/SpanBuilderImpl.java
- inspectit.agent.java.sdk/src/test/java/rocks/inspectit/agent/java/sdk/opentracing/internal/impl/SpanBuilderImplTest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/ServerInterceptor.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/ServerRequestAdapter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/SpanContextStore.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/empty/EmptyRequestAdapter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/HttpServerRequestAdapter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/impl/JavaHttpServerRequest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/mq/MQRequestAdapter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/store/NoopSpanContextStore.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/remote/server/http/JavaHttpRemoteServerSensorTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/remote/server/manual/ManualRemoteServerSensorTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/remote/server/mq/JmsListenerRemoteServerSensorTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/tracing/core/ServerInterceptorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/276)
> INSPECTIT-2408: Span context store support

- inspectit.server/src/main/external-resources/ci/schema/ciSchema.xsd
- inspectit.server/src/main/java/rocks/inspectit/server/ci/ConfigurationInterfaceManager.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/export/ConfigurationInterfaceImportData.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/jaxb/JAXBTransformator.java
- inspectit.shared.cs/src/test/java/rocks/inspectit/shared/cs/jaxb/JAXBTransformatorTest.java
- inspectit.shared.cs/src/test/java/rocks/inspectit/shared/cs/jaxb/NonSchemaAwareTestData.java
- inspectit.shared.cs/src/test/resources/rocks/inspectit/shared/cs/jaxb/schema.xsd
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/281)
> INSPECTIT-2425: CI import data to save schema version

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/wizard/page/DefineDataProcessorsWizardPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/285)
> INSPECTIT-2430: Recording to extract invocations always

- inspectit.ui.rcp/src/main/resources/plugin.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/288)
> INSPECTIT-2434: Enable editing of CI elements

- inspectit.server/src/main/external-resources/config/default.xml
- inspectit.server/src/main/external-resources/config/schema/configurationSchema.xsd
- inspectit.server/src/main/java/rocks/inspectit/server/property/PropertyManager.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/cmr/property/configuration/SingleProperty.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/cmr/property/configuration/impl/StringProperty.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/property/control/impl/StringPropertyControl.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/289)
> INSPECTIT-2435: Hide passwords in the CMR configuration (ui and log)

- inspectit.server/src/main/java/rocks/inspectit/server/influx/util/QueryResultWrapper.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/InvocationDataAccessService.java
- inspectit.server/src/main/java/rocks/inspectit/server/util/CacheIdGenerator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/293)
> INSPECTIT-2437,INSPECTIT-2438: Fixed open invocations with alert id

- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/eum/html/DecodingHtmlScriptInjectorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/304)
> INSPECTIT-2464: Fixed DecodingHtmlScriptInjectorTest for Java 8

- inspectit.server/src/test/java/rocks/inspectit/server/influx/dao/InfluxDBDaoTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/309)
> INSPECTIT-2415: Fixed unit tests for the InfluxDBDao

- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/tracing/data/SpanIdent.java
Fixes #305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/306)
> INSPECTIT-2469: Fixed json serialization for SpanIdent

- inspectit.root.gradle
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/serializer/schema/ClassSchemaManager.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/comparator/AggregatedExceptionSensorDataComparatorEnum.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/comparator/InvocationSequenceDataComparatorEnum.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/storage/processor/impl/DataAggregatorProcessor.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/InspectIT.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/editor/tree/input/InvocDetailInputController.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/form/CmrRepositoryPropertyForm.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/handlers/DeleteStorageHandler.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/model/TreeModelManager.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/preferences/page/CmrRepositoryPreferencePage.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/view/impl/DataExplorerView.java
- resources/config/findbugs/findBugsExcludeFilter.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/302)
> INSPECTIT-2466: Updated FindBugs to 3.0.1

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/310)
> INSPECTIT-2473: end user monitoring description in the readme

- inspectit.agent.java/src/main/resources/js/inspectit_jsagent_base.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/300)
> INSPECTIT-2454: Updated browser and OS matching in the JS agent

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/instrumentation/asm/AbstractMethodInstrumenter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/instrumentation/asm/ConstructorInstrumenter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/instrumentation/asm/MethodInstrumenter.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/292)
> INSPECTIT-2436: Optimized asm byte-code generation

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/SpringAgent.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/config/impl/ConfigurationStorage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/313)
> INSPECTIT-2463: Log the agent version at the very beginning

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/handlers/OpenAlertHandler.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/311)
> INSPECTIT-2483: Open Alert dialog throws NPE

- inspectit.shared.all/src/test/java/rocks/inspectit/shared/all/util/ExecutorServiceUtilsTest.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/InspectIT.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/editor/AgentMappingEditor.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/editor/ApplicationDefinitionEditor.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/editor/EnvironmentEditor.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/editor/ProfileEditor.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/handler/InstrumentationUpdateHandler.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/wizard/AbstractAlertDefinitionWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/wizard/CreateAlertDefinitionWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/wizard/CreateEnvironmentWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/wizard/CreateProfileWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/wizard/EditAlertDefinitionWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/wizard/page/AlertSourceDefinitionWizardPage.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/dialog/AlertSelectionDialog.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/dialog/ProgressDialog.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/editor/tree/DeferredTreeViewer.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/handlers/StopRecordingHanlder.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/job/BlockingJob.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/job/UpdateRepositoryJob.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/CmrRepositoryDefinition.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/CmrRepositoryManager.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/service/cmr/proxy/ServiceInterfaceDelegateInterceptor.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/storage/InspectITStorageManager.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/tester/CmrOnlineStatusTester.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/view/impl/DataExplorerView.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/view/impl/RepositoryManagerView.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/wizard/CreateStorageWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/wizard/StartRecordingWizard.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/wizard/page/DefineCmrWizardPage.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/314)
> INSPECTIT-2457: Execute all UI service calls in a background task

- dependencies.gradle
- inspectit.server.diagnosis/inspectit.server.diagnosis.gradle
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/DiagnosisService.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/IDiagnosisResultNotificationService.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/IDiagnosisService.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/ProblemOccurrenceResultCollector.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/aggregation/AggregatedDiagnosisData.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/aggregation/DiagnosisDataAggregationPerformer.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/aggregation/DiagnosisDataAggregator.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/data/CauseCluster.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/RuleConstants.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/DiagnosisServiceTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/ProblemOccurrenceResultCollectorTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/aggregation/DiagnosisDataAggregationPerformerTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/aggregation/DiagnosisDataAggregatorTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/data/CauseClusterTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/testrules/RuleA.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/testrules/RuleB.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/testrules/RuleC.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/testrules/RuleD.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/diagnosis/AggregatedDiagnosisTimerData.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/diagnosis/CauseStructure.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/diagnosis/DiagnosisTimerData.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/diagnosis/InvocationIdentifier.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/diagnosis/ProblemOccurrence.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/diagnosis/RootCause.java
This commit includes the Diagnosis Service into the server.diagnosis. The Diagnosis Service is not yet active meaning it is not mounted into the CMR process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/265)
> INSPECTIT-2060: Create Diagnosis Service

- inspectit.ui.rcp/inspectit.ui.rcp.gradle
- inspectit.ui.rcp/src/main/resources/inspectIT.product
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/323)
> INSPECTIT-2471: Usability problems in inspectIT UI with macosx 10.12.5

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/transformer/SpanContextTransformer.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/transformer/SpanTransformer.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/invocationsequence/InvocationSequenceHookTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/tracing/core/transformer/SpanContextTransformerTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/tracing/core/transformer/SpanTransformerTest.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/tracing/data/AbstractSpan.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/tracing/data/Span.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/tracing/data/SpanIdent.java
- inspectit.shared.all/src/main/resources/schema/AbstractSpan.sch
- inspectit.shared.all/src/main/resources/schema/SpanIdent.sch
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/indexing/query/factory/impl/SpanQueryFactory.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/editor/tree/util/TraceTreeData.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/328)
> INSPECTIT-2499: Moved parent reference from SpanIdent to Span.

- .gitignore
- dependencies.gradle
- inspectit.root.gradle
- inspectit.server.diagnosis/.classpath
- inspectit.server.diagnosis/inspectit.server.diagnosis.gradle
- inspectit.server.diagnosis/src/jmh/java/rocks/inspectit/server/diagnosis/engine/session/SessionPerfTest.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/data/CauseCluster.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/data/DiagnosisHelper.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/InvocationSequenceDataIterator.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/impl/CauseStructureRule.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/impl/GlobalContextRule.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/impl/ProblemCauseRule.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/impl/ProblemContextRule.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/impl/TimeWastingOperationsRule.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/data/CauseClusterTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/data/DiagnosisHelperTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/InvocationSequenceDataIteratorTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/impl/CauseStructureRuleTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/impl/GlobalContextRuleTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/impl/ProblemCauseRuleTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/impl/ProblemContextRuleTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/impl/TimeWastingOperationsRuleTest.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/InvocationSequenceDataHelper.java
Added Generic Rules and its tests.
INSPECTIT-2059: Generic diagnosis rules
INSPECTIT-2059, INSPECTIT-2347, INSPECTIT-2460: Generic diagnosis rules
Added generic rules and its tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/319)
> INSPECTIT-2059, INSPECTIT-2347, INSPECTIT-2460: Generic diagnosis rules

- inspectit.shared.all/src/test/java/rocks/inspectit/shared/all/storage/nio/stream/ExtendedByteBufferOutputStreamTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/330)
> INSPECTIT-2502: Fixed ExtendedByteBufferOutputStreamTest zero write fail

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/method/remote/client/http/ApacheHttpClientV40Sensor.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/method/remote/client/http/SpringRestTemplateClientSensor.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/method/remote/client/http/UrlConnectionSensor.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/empty/EmptyRequestAdapter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/AsyncHttpClientRequestAdapter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/HttpClientRequestAdapter.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/ClientHttpRequest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/HttpRequest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/impl/ApacheHttpClientV40HttpClientRequest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/impl/JavaHttpServerRequest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/impl/JettyHttpClientV61HttpClientRequest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/impl/SpringRestTemplateHttpClientRequest.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/tracing/core/adapter/http/data/impl/UrlConnectionHttpClientRequestResponse.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/remote/client/http/ApacheHttpClientV40SensorTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/method/remote/client/http/SpringRestTemplateClientSensorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/334)
> INSPECTIT-2505: Fixed tracing with http request forwarding

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/analyzer/impl/ByteCodeAnalyzer.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/IConnection.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnection.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/jmx/JmxSensor.java
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/stats/AgentStatisticsLogger.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/analyzer/impl/ByteCodeAnalyzerTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/connection/impl/KryoNetConnectionTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/jmx/JmxSensorTest.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/stats/AgentStatisticsLoggerTest.java
- inspectit.server/src/main/java/rocks/inspectit/server/util/AgentStatusDataProvider.java
- inspectit.server/src/test/java/rocks/inspectit/server/instrumentation/NextGenInstrumentationManagerTest.java
- inspectit.server/src/test/java/rocks/inspectit/server/util/AgentStatusDataProviderTest.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/communication/data/cmr/AgentStatusData.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/formatter/TextFormatter.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/326)
> INSPECTIT-2322: Agent limited after CMR restart and agent re-connection

- inspectit.server/src/test/java/rocks/inspectit/server/util/AgentStatusDataProviderTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/337)
> INSPECTIT-2514: Fixed AgentStatusDataProviderTest

- inspectit.server/src/main/java/rocks/inspectit/server/influx/dao/InfluxDBDao.java
- inspectit.server/src/test/java/rocks/inspectit/server/influx/dao/InfluxDBDaoTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/340)
> INSPECTIT-2493: Cannot connect to fresh InfluxDB

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/config/impl/ConfigurationStorage.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/config/impl/ConfigurationStorageTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/344)
> INSPECTIT-2490: CR in end of agentName in influx db

- inspectit.server/src/main/external-resources/ci/schema/ciSchema.xsd
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/valuesource/StringValueSource.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/business/valuesource/impl/AgentNameValueSource.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/storage/serializer/SerializationManagerPostProcessor.java
- inspectit.shared.cs/src/test/java/rocks/inspectit/shared/cs/ci/business/valuesource/impl/AgentNameValueSourceTest.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/editor/ApplicationDefinitionEditor.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/part/business/AgentRuleEditingElement.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/part/business/DynamicNameExtractionPart.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/part/business/MatchingRulesEditingElementFactory.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/349)
> INSPECTIT-2192: Add agent rule to application definition

- inspectit.server/src/main/java/rocks/inspectit/server/instrumentation/config/ConfigurationResolver.java
- inspectit.server/src/test/java/rocks/inspectit/server/instrumentation/config/ConfigurationResolverTest.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/ci/form/part/AgentMappingPart.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/348)
> INSPECTIT-2187: More configuration possibilities for the Agent Mapping

- inspectit.server/src/main/java/rocks/inspectit/server/dao/InvocationDataDao.java
- inspectit.server/src/main/java/rocks/inspectit/server/dao/impl/BufferInvocationDataDaoImpl.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/InvocationDataAccessService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/AlertRestfulService.java
- inspectit.server/src/main/java/rocks/inspectit/server/service/rest/InvocationSequenceRestfulService.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/ci/AbstractCiData.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/cmr/service/IInvocationDataAccessService.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/indexing/query/factory/impl/InvocationSequenceDataQueryFactory.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/jaxb/AbstractSchemaVersionAware.java
- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/repository/service/storage/StorageInvocationDataAccessService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/218)
> INSPECTIT-2253: Extend Restful API for alert service

- inspectit.server/src/main/java/rocks/inspectit/server/processor/impl/EUMCorrelationCmrProcessor.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/354)
> INSPECIT-2529: Fixed disappearing pageload-traces on cached sites.

- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/sensor/jmx/JmxSensor.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/sensor/jmx/JmxSensorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/359)
> INSPECTIT-2534: JMX sensor does not handle run-time exceptions

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/editor/text/input/SqlInvocSummaryTextInputController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/365)
> INSPECTIT-2541: fixed SQL summary in the invocation sub-view

- dependencies.gradle
- inspectit.agent.java/src/main/java/rocks/inspectit/agent/java/javaagent/JavaAgent.java
- inspectit.agent.java/src/test/java/rocks/inspectit/agent/java/util/ReflectionCacheTest.java
- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/util/UnderlyingSystemInfo.java
- resources/config/findbugs/findBugsExcludeFilter.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/368)
> INSPECTIT-2544: agent to support java 9

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/handlers/OpenUrlHandler.java
- inspectit.ui.rcp/src/main/resources/content/static/welcome.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/362)
> INSPECTIT-2538: updated support links in the UI

- inspectit.ui.rcp/src/main/java/rocks/inspectit/ui/rcp/view/impl/StorageManagerView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/370)
> INSPECTIT-2545: fixed storage properties on/off without selected storage

- README.md
- inspectit.agent.java.sdk/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/369)
> INSPECTIT-2532: updated readme for the 1.8 final release

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/374)
> INSPECTIT-2557: Adding inspectIT's youtube video to the README

- inspectit.server/src/main/java/rocks/inspectit/server/influx/builder/eum/EUMCachingParentPointBuilder.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/375)
> Fixed race conditions in EUM influx point builder.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/383)
> INSPECTIT-2563: link to road-map announcement in the README.MD

- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/ProblemOccurrenceResultCollector.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/impl/GlobalContextRule.java
- inspectit.server.diagnosis/src/main/java/rocks/inspectit/server/diagnosis/service/rules/impl/TimeWastingOperationsRule.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/ProblemOccurrenceResultCollectorTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/impl/GlobalContextRuleTest.java
- inspectit.server.diagnosis/src/test/java/rocks/inspectit/server/diagnosis/service/rules/impl/TimeWastingOperationsRuleTest.java
- inspectit.server/src/main/java/rocks/inspectit/server/influx/builder/ProblemOccurrencePointBuilder.java
- inspectit.server/src/main/java/rocks/inspectit/server/influx/constants/Series.java
- inspectit.server/src/test/java/rocks/inspectit/server/influx/builder/ProblemOccurrencePointBuilderTest.java
- inspectit.shared.cs/src/main/java/rocks/inspectit/shared/cs/communication/data/diagnosis/ProblemOccurrence.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/382)
> INSPECTIT-2543: Diagnosis service sometimes fails to conduct analysis

- README.md
- inspectit.ui.rcp/inspectit.ui.rcp.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/384)
> INSPECTIT-2560: added shebang line to the run.sh in mac UI

- inspectit.shared.all/src/main/java/rocks/inspectit/shared/all/kryonet/TcpConnection.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit/409)
> INSPECTIT-2574: fixed a typo in original commit
